!YAMLDict
data: !YAMLDict
  image: !YAMLDict {cropped_image_size: 64, normalize: true, pixel_max: 1.0, pixel_min: 0.0,
    random_crop: true}
  roi: !YAMLDict {roi_attribute_name: centroid, roi_side_length: 11}
simulation: !YAMLDict {}
train: !YAMLDict {batch_size: 128, gamma: 0.1, learning_rate: 0.001, momentum: 0.9,
  weight_decay: 0.0005}
